from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

from core.models import EngineId
from engines.rpgmaker.audit import RpgMakerCoverageAuditor
from engines.rpgmaker.mv_plugin_discovery import APPLY_VERIFIED, discover_mv_plugin_commands
from engines.rpgmaker.plugin_inventory import load_plugin_inventory
from engines.rpgmaker.plugin_visibility import (
    VisibilityClassification,
    analyze_plugin_visibility,
)


class RpgMakerPluginVisibilityTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name)
        self.game = self.root / "game"
        self.plugins = self.game / "js/plugins"
        self.plugins.mkdir(parents=True)
        data = self.game / "data"
        data.mkdir()
        (self.game / "js/rpg_core.js").write_text("// synthetic", encoding="utf-8")
        (data / "System.json").write_text("{}", encoding="utf-8")
        (data / "Map001.json").write_text(
            json.dumps({"displayName": "", "events": []}), encoding="utf-8"
        )

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def _inventory(self, sources: dict[str, tuple[bool, str, dict[str, object]]]):
        records = []
        for name, (enabled, source, parameters) in sources.items():
            records.append(
                {
                    "name": name,
                    "status": enabled,
                    "description": "",
                    "parameters": parameters,
                }
            )
            (self.plugins / f"{name}.js").write_text(source, encoding="utf-8")
        config = self.game / "js/plugins.js"
        config.write_text(
            "var $plugins = " + json.dumps(records, ensure_ascii=False) + ";",
            encoding="utf-8",
        )
        return load_plugin_inventory(config, self.plugins)

    def _findings(self, sources):
        return analyze_plugin_visibility(self._inventory(sources)).findings

    def _inventory_from_registry(
        self,
        registry_text: str,
        plugin_names: tuple[str, ...],
    ):
        for name in plugin_names:
            (self.plugins / f"{name}.js").write_text(
                "var synthetic = true;", encoding="utf-8"
            )
        config = self.game / "js/plugins.js"
        config.write_text(registry_text, encoding="utf-8", newline="")
        return load_plugin_inventory(config, self.plugins)

    def test_active_inventory_retains_parameters_and_source_evidence(self) -> None:
        inventory = self._inventory(
            {
                "Enabled": (True, "var x = 1;", {"Caption": "private value"}),
                "Disabled": (False, "var y = 1;", {}),
            }
        )
        self.assertEqual(2, inventory.plugin_count)
        self.assertEqual(("Enabled",), tuple(item.name for item in inventory.active_plugins))
        enabled = inventory.active_plugins[0]
        self.assertEqual(0, enabled.load_order)
        self.assertEqual("private value", enabled.parameters["Caption"])
        self.assertTrue(enabled.source_available)
        self.assertEqual(64, len(enabled.source_sha256 or ""))

    def test_registry_without_trailing_comma_preserves_status_behavior(self) -> None:
        records = [
            {"name": "Enabled", "status": True, "parameters": {}},
            {"name": "Disabled", "status": False, "parameters": {}},
        ]
        inventory = self._inventory_from_registry(
            "var $plugins = " + json.dumps(records) + ";",
            ("Enabled", "Disabled"),
        )

        self.assertEqual(2, inventory.plugin_count)
        self.assertEqual(("Enabled",), tuple(x.name for x in inventory.active_plugins))
        self.assertFalse(any(x.severity == "error" for x in inventory.issues))

    def test_registry_accepts_terminal_array_comma_with_crlf(self) -> None:
        record = {"name": "Trailing", "status": True, "parameters": {}}
        payload = json.dumps([record])
        registry = "// Generated by RPG Maker.\r\nvar $plugins =\r\n" + payload[:-1] + ",\r\n];\r\n"

        inventory = self._inventory_from_registry(registry, ("Trailing",))

        self.assertEqual(1, inventory.plugin_count)
        self.assertEqual("Trailing", inventory.active_plugins[0].name)
        self.assertFalse(any(x.severity == "error" for x in inventory.issues))

    def test_registry_preserves_commas_inside_parameter_strings(self) -> None:
        parameters = {
            "Csv": "left,right,center",
            "JsonText": '{"items":["a,b","c"]}',
        }
        record = {"name": "CommaText", "status": True, "parameters": parameters}
        payload = json.dumps([record])
        registry = "var $plugins = " + payload[:-1] + ",];"

        inventory = self._inventory_from_registry(registry, ("CommaText",))

        self.assertEqual(parameters, dict(inventory.active_plugins[0].parameters))

    def test_registry_preserves_escaped_quotes_and_backslashes(self) -> None:
        escaped = 'path\\folder and "quoted" text'
        record = {
            "name": "Escaped",
            "status": True,
            "parameters": {"Escaped": escaped},
        }
        payload = json.dumps([record])
        registry = "var $plugins = " + payload[:-1] + ",];"

        inventory = self._inventory_from_registry(registry, ("Escaped",))

        self.assertEqual(escaped, inventory.active_plugins[0].parameters["Escaped"])

    def test_registry_rejects_unsupported_syntax_and_malformed_entries(self) -> None:
        cases = (
            (
                "var $plugins = [{name: 'Unsupported', status: true, parameters: {}}];",
                "Unsupported",
            ),
            (
                'var $plugins = [{"name":"Malformed","status":true,"parameters":[]}];',
                "Malformed",
            ),
        )
        for registry, plugin_name in cases:
            with self.subTest(plugin=plugin_name):
                inventory = self._inventory_from_registry(registry, (plugin_name,))
                self.assertEqual(0, inventory.plugin_count)
                self.assertTrue(any(x.severity == "error" for x in inventory.issues))

    def test_direct_visible_plugin_parameter_is_verified(self) -> None:
        findings = self._findings(
            {
                "Visible": (
                    True,
                    """
var parameters = PluginManager.parameters('Visible');
var caption = parameters['Caption'];
Window_Test.prototype.paint = function() { this.drawText(caption, 0, 0, 200); };
""",
                    {"Caption": "not persisted"},
                )
            }
        )
        item = next(row for row in findings if row.source_kind == "plugin_parameter")
        self.assertEqual(VisibilityClassification.VERIFIED_VISIBLE.value, item.classification)
        self.assertEqual("drawText", item.sink)

    def test_numeric_plugin_parameter_is_internal(self) -> None:
        findings = self._findings(
            {
                "Config": (
                    True,
                    """
var parameters = PluginManager.parameters('Config');
var speed = Number(parameters['Speed']);
if (speed > 0) { this._fastMode = true; }
""",
                    {"Speed": "4"},
                )
            }
        )
        item = next(row for row in findings if row.source_kind == "plugin_parameter")
        self.assertEqual(VisibilityClassification.INTERNAL.value, item.classification)

    def test_note_regex_capture_to_draw_text_is_verified(self) -> None:
        findings = self._findings(
            {
                "NoteRender": (
                    True,
                    """
var match = data.note.match(/<[^:]+:(.*?)>/);
var visible = match[1];
Window_Test.prototype.paint = function() { this.drawText(visible, 0, 0, 200); };
""",
                    {},
                )
            }
        )
        item = next(row for row in findings if row.source_kind == "note")
        self.assertEqual(VisibilityClassification.VERIFIED_VISIBLE.value, item.classification)
        self.assertIn("literal_regex_match", item.transform_evidence)
        self.assertIn("capture[1]", item.transform_evidence)

    def test_note_control_keyword_is_internal(self) -> None:
        findings = self._findings(
            {
                "NoteControl": (
                    True,
                    "if (data.note.indexOf('CONTROL_TOKEN') >= 0) { enabled = false; }",
                    {},
                )
            }
        )
        item = next(row for row in findings if row.source_kind == "note")
        self.assertEqual(VisibilityClassification.INTERNAL.value, item.classification)

    def test_meta_literal_access_reaching_command_label_is_verified(self) -> None:
        sources = (
            "var label = data.meta['MenuLabel'];",
            "var metadata = data.meta; var label = metadata.MenuLabel;",
        )
        for source in sources:
            with self.subTest(source=source):
                findings = self._findings(
                    {
                        "MetaLabel": (
                            True,
                            source + " target.addCommand(label, 'symbol');",
                            {},
                        )
                    }
                )
                item = next(row for row in findings if row.source_kind == "meta")
                self.assertEqual(
                    VisibilityClassification.VERIFIED_VISIBLE.value,
                    item.classification,
                )
                self.assertEqual("addCommand", item.sink)

    def test_supported_literal_transforms_remain_explainable(self) -> None:
        expressions = {
            "literal_split": "parameters['Text'].split('|')[0]",
            "literal_slice": "parameters['Text'].slice(1)",
            "literal_substr": "parameters['Text'].substr(1, 4)",
            "literal_substring": "parameters['Text'].substring(1, 4)",
            "literal_replace": "parameters['Text'].replace(/x/g, '')",
        }
        for expected, expression in expressions.items():
            with self.subTest(transform=expected):
                findings = self._findings(
                    {
                        "Transform": (
                            True,
                            f"""
var parameters = PluginManager.parameters('Transform');
var label = {expression};
target.drawText(label, 0, 0, 100);
""",
                            {"Text": "value"},
                        )
                    }
                )
                item = next(
                    row for row in findings if row.source_kind == "plugin_parameter"
                )
                self.assertEqual(
                    VisibilityClassification.VERIFIED_VISIBLE.value,
                    item.classification,
                )
                self.assertIn(expected, item.transform_evidence)

    def test_japanese_parameter_value_does_not_promote_unknown_usage(self) -> None:
        findings = self._findings(
            {
                "Unknown": (
                    True,
                    "var parameters = PluginManager.parameters('Unknown'); var value = parameters['Value'];",
                    {"Value": "日本語"},
                )
            }
        )
        item = next(row for row in findings if row.source_kind == "plugin_parameter")
        self.assertEqual(VisibilityClassification.UNKNOWN.value, item.classification)

    def test_two_hop_helper_to_draw_text_ex_is_verified(self) -> None:
        findings = self._findings(
            {
                "Helpers": (
                    True,
                    """
var parameters = PluginManager.parameters('Helpers');
var help = parameters['Help'];
function renderHelp(text) { target.drawTextEx(text, 0, 0); }
function routeHelp(value) { renderHelp(value); }
routeHelp(help);
""",
                    {"Help": "hidden raw"},
                )
            }
        )
        item = next(row for row in findings if row.source_kind == "plugin_parameter")
        self.assertEqual(VisibilityClassification.VERIFIED_VISIBLE.value, item.classification)
        self.assertEqual("drawTextEx", item.sink)
        self.assertLessEqual(item.helper_depth, 2)

    def test_dynamic_property_is_not_verified(self) -> None:
        findings = self._findings(
            {
                "Dynamic": (
                    True,
                    """
var parameters = PluginManager.parameters('Dynamic');
var value = parameters[keyName];
unknownCallback(value);
""",
                    {"A": "value"},
                )
            }
        )
        item = next(row for row in findings if row.source_kind == "plugin_parameter")
        self.assertIn(
            item.classification,
            {
                VisibilityClassification.CONDITIONAL_VISIBLE.value,
                VisibilityClassification.UNKNOWN.value,
            },
        )

    def test_eval_consumption_is_unsafe(self) -> None:
        findings = self._findings(
            {
                "Unsafe": (
                    True,
                    """
var parameters = PluginManager.parameters('Unsafe');
var expression = parameters['Expression'];
eval(expression);
""",
                    {"Expression": "value"},
                )
            }
        )
        item = next(row for row in findings if row.source_kind == "plugin_parameter")
        self.assertEqual(VisibilityClassification.UNSAFE.value, item.classification)

    def test_mixed_display_and_logic_use_is_downgraded(self) -> None:
        findings = self._findings(
            {
                "Mixed": (
                    True,
                    """
var parameters = PluginManager.parameters('Mixed');
var label = parameters['Label'];
target.drawText(label, 0, 0, 100);
if (label === 'CONTROL_TOKEN') { enabled = false; }
""",
                    {"Label": "value"},
                )
            }
        )
        item = next(row for row in findings if row.source_kind == "plugin_parameter")
        self.assertEqual(VisibilityClassification.CONDITIONAL_VISIBLE.value, item.classification)
        self.assertTrue(item.mixed_use)

    def test_conflicting_active_plugins_record_ambiguity(self) -> None:
        findings = self._findings(
            {
                "Renderer": (
                    True,
                    "var value = data.note; target.drawText(value, 0, 0, 100);",
                    {},
                ),
                "Controller": (
                    True,
                    "if (data.note.indexOf('CONTROL_TOKEN') >= 0) { enabled = false; }",
                    {},
                ),
            }
        )
        note_rows = [row for row in findings if row.source_kind == "note"]
        self.assertEqual(2, len(note_rows))
        self.assertTrue(all(row.ambiguity for row in note_rows))
        self.assertTrue(
            all(
                row.classification
                == VisibilityClassification.CONDITIONAL_VISIBLE.value
                for row in note_rows
            )
        )

    def test_disabled_plugin_is_excluded_from_visibility_analysis(self) -> None:
        report = analyze_plugin_visibility(
            self._inventory(
                {
                    "Off": (
                        False,
                        "var p=PluginManager.parameters('Off'); target.drawText(p['Text']);",
                        {"Text": "value"},
                    )
                }
            )
        )
        self.assertEqual(0, report.active_plugin_count)
        self.assertEqual(0, report.analyzed_plugin_count)
        self.assertEqual([], report.findings)

    def test_existing_mv_356_discovery_still_resolves(self) -> None:
        inventory = self._inventory(
            {
                "Command": (
                    True,
                    """
Game_Interpreter.prototype.pluginCommand = function(command, args) {
 if (command === 'Notice') { $gameMessage.add(args.join(' ')); }
};
""",
                    {},
                )
            }
        )
        report = discover_mv_plugin_commands(
            self.game / "js/plugins.js", self.plugins, inventory=inventory
        )
        self.assertEqual(APPLY_VERIFIED, report.observations[0].classification)

    def test_audit_adds_machine_readable_plugin_visibility_without_raw_values(self) -> None:
        self._inventory(
            {
                "Audit": (
                    True,
                    """
var p = PluginManager.parameters('Audit');
var label = p['Label'];
target.drawText(label, 0, 0, 100);
""",
                    {"Label": "private parameter value"},
                )
            }
        )
        report = RpgMakerCoverageAuditor(EngineId.RPGMAKER_MV).audit(self.game)
        visible = report.plugin_visibility
        self.assertEqual(1, visible["active_plugin_count"])
        self.assertEqual(1, visible["analyzed_plugin_count"])
        self.assertEqual(1, visible["classification_counts"]["VERIFIED_VISIBLE"])
        self.assertNotIn("private parameter value", json.dumps(report.to_json_dict()))


if __name__ == "__main__":
    unittest.main()
